(function () {
  var BASE = typeof WIKI_BASE !== 'undefined' ? WIKI_BASE : '';

  function resolve(url) {
    return BASE + url;
  }

  // Fallback for file:// or when search.json hasn't loaded yet (also keeps offline usable)
  var SEARCH_INDEX_FALLBACK = [
    { title: 'Overview', url: 'index.html', section: 'Home',
      excerpt: 'Welcome to AuraSMP: enchantments, scrolls, potions, a wilder world and little animations.' },
    { title: 'Arcanum', url: 'Enchanting/index.html', section: 'Mods',
      excerpt: 'Gear never breaks, fewer but more meaningful enchantments.' },
    { title: 'Folio', url: 'Folio/index.html', section: 'Mods',
      excerpt: 'Craft scrolls, find spellbooks, cast spells.' },
    { title: 'Panacea', url: 'Panacea/index.html', section: 'Mods',
      excerpt: 'New potions, potion mixing, and tipped swords.' },
    { title: 'Vantage: World', url: 'Worldgen/index.html', section: 'Mods',
      excerpt: '100+ biomes and hidden structures.' },
    { title: 'Puppeteer: Animations', url: 'Puppeteer/index.html', section: 'Mods',
      excerpt: 'Subtle automatic animations to give a little life to the world.' },
    { title: 'Gear', url: 'Gear/index.html', section: 'Sections',
      excerpt: 'Nothing here yet!' },
    { title: 'Progression', url: 'Progression/index.html', section: 'Sections',
      excerpt: 'Nothing here yet!' }
  ];

  // Will be replaced by search.json once fetched; starts as fallback so search works instantly
  var SEARCH_INDEX = SEARCH_INDEX_FALLBACK.slice();
  var searchIndexPromise = null;

  function loadSearchIndex() {
    // Fully static: just fetches wiki/search.json generated by scripts/build-search.mjs
    try {
      return fetch(resolve('search.json'), { cache: 'no-cache' })
        .then(function (r) { if (!r.ok) throw new Error(r.status + ' ' + r.statusText); return r.json(); })
        .then(function (data) {
          if (Array.isArray(data) && data.length) SEARCH_INDEX = data;
        })
        .catch(function () {
          // keep fallback (e.g. file:// CORS or 404)
        });
    } catch (e) {
      return Promise.resolve();
    }
  }
  searchIndexPromise = loadSearchIndex();

  function escapeHtml(s) {
    return s.replace(/[&<>"']/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
    });
  }

  function matches(entry, q) {
    var hay = (entry.title + ' ' + entry.section + ' ' + entry.excerpt).toLowerCase();
    return hay.indexOf(q) !== -1;
  }

  function initSiteSearch() {
    var input = document.getElementById('site-search');
    var results = document.getElementById('site-search-results');
    if (!input || !results) return;

    var activeIndex = -1;
    var current = [];

    // Re-run search if index finishes loading after user already typed
    if (searchIndexPromise) {
      searchIndexPromise.then(function () {
        if (input.value.trim()) {
          var q = input.value.trim().toLowerCase();
          render(SEARCH_INDEX.filter(function (e) { return matches(e, q); }));
        }
      });
    }

    function render(list) {
      current = list;
      activeIndex = -1;
      if (!list.length) {
        results.innerHTML = '<p class="search-empty">No matches. Try a different term.</p>';
        results.hidden = false;
        return;
      }
      results.innerHTML = list.map(function (entry, i) {
        return '<a href="' + resolve(entry.url) + '" data-i="' + i + '">' +
          '<span class="result-section">' + escapeHtml(entry.section) + '</span>' +
          '<div class="result-title">' + escapeHtml(entry.title) + '</div>' +
          '<div class="result-excerpt">' + escapeHtml(entry.excerpt) + '</div>' +
          '</a>';
      }).join('');
      results.hidden = false;
    }

    function close() {
      results.hidden = true;
      activeIndex = -1;
    }

    input.addEventListener('input', function () {
      var q = input.value.trim().toLowerCase();
      if (!q) { close(); return; }
      render(SEARCH_INDEX.filter(function (e) { return matches(e, q); }));
    });

    input.addEventListener('keydown', function (e) {
      var links = results.querySelectorAll('a');
      if (e.key === 'ArrowDown') {
        e.preventDefault();
        if (!links.length) return;
        activeIndex = (activeIndex + 1) % links.length;
        links.forEach(function (l, i) { l.classList.toggle('is-active', i === activeIndex); });
        links[activeIndex].scrollIntoView({ block: 'nearest' });
      } else if (e.key === 'ArrowUp') {
        e.preventDefault();
        if (!links.length) return;
        activeIndex = (activeIndex - 1 + links.length) % links.length;
        links.forEach(function (l, i) { l.classList.toggle('is-active', i === activeIndex); });
        links[activeIndex].scrollIntoView({ block: 'nearest' });
      } else if (e.key === 'Enter') {
        if (activeIndex >= 0 && links[activeIndex]) {
          window.location.href = links[activeIndex].getAttribute('href');
        } else if (current.length) {
          window.location.href = resolve(current[0].url);
        }
      } else if (e.key === 'Escape') {
        close();
        input.blur();
      }
    });

    document.addEventListener('click', function (e) {
      if (!results.contains(e.target) && e.target !== input) close();
    });

    document.addEventListener('keydown', function (e) {
      if (e.key === '/' && document.activeElement !== input) {
        var tag = (document.activeElement && document.activeElement.tagName) || '';
        if (tag === 'INPUT' || tag === 'TEXTAREA') return;
        e.preventDefault();
        input.focus();
      }
    });
  }

  function initPageSearch() {
    var input = document.getElementById('page-search');
    var countEl = document.getElementById('page-search-count');
    var prevBtn = document.getElementById('page-search-prev');
    var nextBtn = document.getElementById('page-search-next');
    var scope = document.getElementById('page-content-scope');
    if (!input || !scope) return;

    var marks = [];
    var current = -1;

    function clearMarks() {
      marks.forEach(function (m) {
        var parent = m.parentNode;
        if (!parent) return;
        parent.replaceChild(document.createTextNode(m.textContent), m);
        parent.normalize();
      });
      marks = [];
      current = -1;
    }

    function walkAndWrap(root, q) {
      var walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
        acceptNode: function (node) {
          if (!node.nodeValue.trim()) return NodeFilter.FILTER_REJECT;
          if (node.parentNode && node.parentNode.closest('#page-search')) return NodeFilter.FILTER_REJECT;
          return NodeFilter.FILTER_ACCEPT;
        }
      });
      var textNodes = [];
      var n;
      while ((n = walker.nextNode())) textNodes.push(n);

      textNodes.forEach(function (node) {
        var text = node.nodeValue;
        var lower = text.toLowerCase();
        var idx = lower.indexOf(q);
        if (idx === -1) return;

        var frag = document.createDocumentFragment();
        var lastEnd = 0;
        while (idx !== -1) {
          frag.appendChild(document.createTextNode(text.slice(lastEnd, idx)));
          var mark = document.createElement('mark');
          mark.className = 'pf-hit';
          mark.textContent = text.slice(idx, idx + q.length);
          frag.appendChild(mark);
          marks.push(mark);
          lastEnd = idx + q.length;
          idx = lower.indexOf(q, lastEnd);
        }
        frag.appendChild(document.createTextNode(text.slice(lastEnd)));
        node.parentNode.replaceChild(frag, node);
      });
    }

    function updateCount() {
      if (!marks.length) {
        countEl.textContent = input.value ? '0 results' : '';
      } else {
        countEl.textContent = (current + 1) + ' of ' + marks.length;
      }
      prevBtn.disabled = marks.length === 0;
      nextBtn.disabled = marks.length === 0;
    }

    function goTo(i) {
      if (!marks.length) return;
      if (marks[current]) marks[current].classList.remove('pf-current');
      current = (i + marks.length) % marks.length;
      marks[current].classList.add('pf-current');
      marks[current].scrollIntoView({ block: 'center', behavior: 'smooth' });
      updateCount();
    }

    function runSearch() {
      clearMarks();
      var q = input.value.trim().toLowerCase();
      if (q.length > 0) {
        walkAndWrap(scope, q);
        if (marks.length) goTo(0);
      }
      updateCount();
    }

    input.addEventListener('input', runSearch);
    input.addEventListener('keydown', function (e) {
      if (e.key === 'Enter') {
        e.preventDefault();
        if (e.shiftKey) goTo(current - 1); else goTo(current + 1);
      } else if (e.key === 'Escape') {
        input.value = '';
        runSearch();
        input.blur();
      }
    });
    prevBtn.addEventListener('click', function () { goTo(current - 1); });
    nextBtn.addEventListener('click', function () { goTo(current + 1); });
  }

  function initToc() {
    var toc = document.querySelector('.toc');
    if (!toc) return;
    var links = Array.prototype.slice.call(toc.querySelectorAll('a'));
    var sections = links
      .map(function (l) { return document.querySelector(l.getAttribute('href')); })
      .filter(Boolean);
    if (!sections.length) return;

    var observer = new IntersectionObserver(function (entries) {
      entries.forEach(function (entry) {
        var link = toc.querySelector('a[href="#' + entry.target.id + '"]');
        if (!link) return;
        if (entry.isIntersecting) {
          links.forEach(function (l) { l.classList.remove('is-active'); });
          link.classList.add('is-active');
        }
      });
    }, { rootMargin: '-15% 0px -70% 0px' });

    sections.forEach(function (s) { observer.observe(s); });
  }

  function initMobileNav() {
    var btn = document.getElementById('sidebar-toggle');
    var sidebar = document.querySelector('.sidebar');
    if (!btn || !sidebar) return;
    btn.addEventListener('click', function () {
      sidebar.classList.toggle('is-open');
    });
    document.addEventListener('click', function (e) {
      if (sidebar.classList.contains('is-open') &&
          !sidebar.contains(e.target) && e.target !== btn) {
        sidebar.classList.remove('is-open');
      }
    });
  }

  document.addEventListener('DOMContentLoaded', function () {
    initSiteSearch();
    initPageSearch();
    initToc();
    initMobileNav();
  });
})();
